# Generated by Django 4.1.7 on 2023-04-07 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trafficking", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Customer",
            new_name="Missingperson",
        ),
    ]
